### ISSUE TITLE
1.14.2 Spigot Plugin

### ISSUE THREAD

**Issue by KnowWolf** [cridenour/whitelist#1]
Is there any way to make the whitelist automatically pull to the server rather than having to manually download and upload the whitelist?

**Comment by cridenour** [comment]
Hi @KnowWolf - I don't have any experience with Spigot. If there are any plugins that can reload the whitelist you could use a simple cron job on the server to keep the whitelist up to date. 

I believe MCLink from @dries007 has a Spigot plugin so may be a better fit for your use case.

**Comment by dries007** [comment]
Thanks for the plug :)

MCLink is live-updating because it works differently then this tool. If you have questions about it, feel free to contact me. Here is a link: https://mclink.dries007.net/
